### ISSUE TITLE
rustfmt missing

### ISSUE THREAD

**Issue by ankane** [oxidize-rb/cross-gem-action#110]
Hi @ianks, thanks for creating this! I'm currently testing it with Tokenizers and ran into an error, which I believe is due to [this commit](https://github.com/oxidize-rb/rb-sys/commit/8e9e024ff675e2eb74e186b4825c123ce43081be).

```text
  thread 'main' panicked at 'rustfmt is required to generate bindings', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rb-sys-build-0.9.44/src/bindings.rs:78:9
```

Using the `setup` option to add rustfmt fixes it, but it'd be nice if the action included this.

```yaml
          setup: |
            rustup component add rustfmt
            bundle install
```

**Comment by ianks** [comment]
Hi there, the newest images now include rustfmt. Let me know if that works for you!

**Comment by ankane** [comment]
Thanks @ianks, but still seeing the error.

Workflow: https://github.com/ankane/tokenizers-ruby/blob/b8e42bf0e5be4eb58dd9fffc915a4d6c4caaaae7/.github/workflows/release.yml
CI output: https://github.com/ankane/tokenizers-ruby/actions/runs/3569221870/jobs/5998956489

**Comment by ankane** [comment]
Nevermind, `version: latest` fixed it (which looks like will be the default in a future release - 5d286c263b0a4ec3a82f4caaf58b05b0e7dda0d9).
