### ISSUE TITLE
I think this action or one of its dependencies are using an outdated GitHub Action syntax

### ISSUE THREAD

**Issue by gjtorikian** [oxidize-rb/cross-gem-action#93]
Here's a link to a log file showing the warning: https://github.com/gjtorikian/commonmarker/actions/runs/3269757507/jobs/5377628002#step:4:391

And the notice: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gjtorikian** [comment]
(This might be solved by merging https://github.com/oxidize-rb/cross-gem-action/pull/97)

**Comment by gjtorikian** [comment]
Sorry, but this isn't solved yet @ianks. See https://github.com/gjtorikian/selma/actions/runs/3752129620/jobs/6374106251#step:4:602 for an example: despite pinning the action to `main`, the warnings persist.

**Comment by ianks** [comment]
Any idea what it is??

**Comment by gjtorikian** [comment]
I think I got it: https://github.com/actions/toolkit/pull/1178

`@actions/core` should be bumped to >= 1.10; it's currently `^1.9.0`

**Comment by gjtorikian** [comment]
Closed by merge of #84
